name: waiterbildung

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    image: waiterbildung:latest
    build:
      context: .
    command: sh -c "alembic upgrade head && python main.py"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  email-worker:
    image: waiterbildung:latest
    command: python worker.py email
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - api

  scraper-worker:
    image: waiterbildung:latest
    command: python worker.py scraper
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - api

  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    command: --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rq:
    image: waiterbildung:latest
    build:
      context: .
    command: sh -c "rq-dashboard --bind 0.0.0.0 --port 9181 --url-prefix '/rq' --redis-url ${REDIS_URL}"
    env_file:
      - .env
    depends_on:
      - redis

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
  redis_data:
