name: waiterbildung

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - adminer

  api:
    image: waiterbildung:latest
    command: sh -c "alembic revision --autogenerate -m 'auto' && alembic upgrade head && python main.py"
    build: .
    env_file:
      - .env
    volumes:
      - alembic_versions:/app/alembic/versions
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  email-worker:
    image: waiterbildung:latest
    command: python worker.py email
    env_file:
      - .env
    depends_on:
      - api

  scraper-worker:
    image: waiterbildung:latest
    command: python worker.py scraper
    env_file:
      - .env
    depends_on:
      - api

  rq:
    image: waiterbildung:latest
    command: sh -c "rq-dashboard --bind rq --port 9181 --url-prefix '/rq' --redis-url ${REDIS_URL}"
    env_file:
      - .env
    depends_on:
      - redis

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: postgres

  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  alembic_versions:
