name: poc-scraper

services:
  api:
    image: poc-scraper:latest
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    image: poc-scraper:latest
    command: celery -A app.core.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  celery_flower:
    image: poc-scraper:latest
    command: celery -A app.core.celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      celery_worker:
        condition: service_started

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "${MONGODB_URL}" --quiet
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli -u ${REDIS_URL} ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  mongodb_data:
  mongodb_config:
  redis_data:
