name: poc-scraper

services:
  api:
    image: poc-scraper:latest
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  celery_worker:
    image: poc-scraper:latest
    command: celery -A app.core.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  celery_flower:
    image: poc-scraper:latest
    command: celery -A app.core.celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      celery_worker:
        condition: service_started 

  redis:
    image: redis:alpine
    env_file:
      - .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli -u ${REDIS_URL} ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
