"""auto

Revision ID: 304bc282b451
Revises: ee6ea22c55f1
Create Date: 2025-02-16 23:43:47.807895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304bc282b451'
down_revision: Union[str, None] = 'ee6ea22c55f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'verification_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_token_expires_at')
    # ### end Alembic commands ###
