"""autoa

Revision ID: 9cae49719ce2
Revises: 0f96bb5b224e
Create Date: 2025-02-17 11:14:16.145981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cae49719ce2'
down_revision: Union[str, None] = '0f96bb5b224e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('status', sa.Enum('not_started', 'queued', 'in_progress', 'completed', 'failed', 'cancelled', name='scraperstatus'), nullable=False))
    op.drop_column('institutions', 'scraper_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('scraper_status', postgresql.ENUM('not_started', 'queued', 'in_progress', 'completed', 'failed', 'cancelled', name='scraperstatus'), autoincrement=False, nullable=False))
    op.drop_column('institutions', 'status')
    # ### end Alembic commands ###
