name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost/test --quiet"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Decode .env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE_BASE64 }}
        run: echo "$ENV_FILE" | base64 --decode > .env

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 **/*.py

      - name: Start Python Application
        run: |
          # Start the Python application in the background
          python app.py &
          APP_PID=$!

          # Wait a few seconds to ensure the app starts
          sleep 5

          # Check if the application is still running
          if ! kill -0 $APP_PID; then
            echo "Python application failed to start"
            exit 1
          fi

      - name: Test Celery Worker
        env:
          MONGODB_URL: mongodb://localhost:27017/test
          REDIS_URL: redis://localhost:6379/0
        run: |
          # Start Celery worker in the background
          celery -A app.celery worker --loglevel=info &
          CELERY_PID=$!

          # Wait a few seconds to ensure the worker starts
          sleep 5

          # Check if the Celery worker is still running
          if ! kill -0 $CELERY_PID; then
            echo "Celery worker failed to start"
            exit 1
          fi
